Repository d-edge/foss-acronyms, pull requests merged in 2022-10, with the labels that each got.

#65 Add AFAICT example
  data/acronyms.json
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#69 Add WRT
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#70 Add XP
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#68 Add cmiiw
  data/chat-acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#66 Add AFAIK details, BRB , IRL , DTO , AFK
  data/acronyms.json
  data/chat-acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#71 Add SSOC
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#72 Add acronym for iykyk
  data/chat-acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#73 Add EFK stack
  data/stacks.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#76 Add DX to Acronyms
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#77 Add WYSIWYG to Acronyms
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#81 Update stacks.json with LAMP's examples
  data/stacks.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#79 Add LOL in chat acronyms
  data/chat-acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#78 Add DIP to acronyms
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#80 Add SE, SWE, SRE
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#86 Add Whisper's discussion as example for YMMV
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#87 Add example to CoC
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#89 Add RFP, RFI and RCE acronyms
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#92 Add MVC
  data/acronyms.json
Labels: enhancement, hacktoberfest

#95 Add tyvm acronym and fixed syntax error
  data/acronyms.json
  data/chat-acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#98 Fix wrong link title
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#105 Add GUI
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#104 Add CLI
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#107 Fix PEBCAK definition add added it's variants.
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#109 Added Amazon Web Services in organizations.json
  data/organizations.json
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#116 Add "DoD" acronyms
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#82 Update acronyms.json with RICE
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#112 Add youtube acronym organization
  data/organizations.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#119 #28 Added POCO and POJO
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#120 Add CFP
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#121 Add RTFA, TFA, DAG
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#122 Add CJK
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#125 Add AD (Architectural Decision)
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#126 Add ADR, AKM, and ASR
  data/acronyms.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest
